{% set name = "gevent" %}
{% set version = "1.3.2.post0" %}
{% set sha256 = "5eeec334778cbad059b54fc468b0690db6794fe12a1dada7b70924d1c9ffbeac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Allow-include-flags-to-be-present-in-CFLAGS.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    # cffi 1.4.0 is the general minimum version
    # With Python 3 version 1.11.3 is minimum
    # On windows 1.11.5 is the minimum
    # Rather than special casing each of these use a single minimum version
    - cffi >=1.11.5
    - python
    - setuptools

  build:
    - {{ compiler('c') }}

  run:
    - cffi >=1.11.5
    - python
    - greenlet >=0.4.13

test:
  imports:
    - gevent
    - gevent.libev

about:
  home: http://www.gevent.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Coroutine-based network library'
  description: |
    Gevent uses greenlet to provide a high-level synchronous API on top of the libev event loop.
  doc_url: http://www.gevent.org/contents.html
  dev_url: https://github.com/gevent/gevent

extra:
  recipe-maintainers:
    - nehaljwani
