# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YhSdmNlb+8wdi1GogBSu0Kd/mZm6MhYx+0qgk9eZln+PlO0taYcxq2P6W67RTe4HXGzlhbuvo71dM7EX2ZpMjS9n+eZmiY0+QiB6aWLdtUI0CNQJvJxjqOIccOl4OFR2cBeYxJXBc7r42YzHA+RZhEkwyV7Vlamc8cgzGtyPo9bACYMbprP36z9t1mPESQm5isRrzEufrdtzK+n+2mk/6rldTrcDroUKQ9MJhd6mdi9yweUaA1wkLRM+udqvcN1lHpdsDwqpAuYY+RIouXCMW8gkb2j5P/1aMytmhSDEetz2aSPqKcpPkrJtkDw6OwcXLG68GchQ+ezZZQVw0Y0c238cejZ8kayXsZDyYAwKp0q2OH2vmC8qKP46iIPOUtukEB/l77kz358vOX1/5j4eHNjD+MlnYrCdw9q3EyOUvV9pYHuHWzHB/r6AYuqZx0huAIeY87sfZCFQXuorjnZ6oHdnO7HIWccSGRgFWhPbzniAKfESDnzMjZZNy+RD7bfHvNsORqdHPVLwSKgoEvvhVWpNegucrrB0Ao/aS85bJykrt+3+D6pv7RuZmxhVbjwJq7O/67dMu7dtepn/svyB6yracpMoFJCNQj4UqFxjfX6GKx/oTxHddRHK/4DMSantI+pqB+6hp5L0jbMeb9kE3oS8bBxVC2sKYjfVyCpKjHw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
