travis:
  secure:
    BINSTAR_TOKEN: YhSdmNlb+8wdi1GogBSu0Kd/mZm6MhYx+0qgk9eZln+PlO0taYcxq2P6W67RTe4HXGzlhbuvo71dM7EX2ZpMjS9n+eZmiY0+QiB6aWLdtUI0CNQJvJxjqOIccOl4OFR2cBeYxJXBc7r42YzHA+RZhEkwyV7Vlamc8cgzGtyPo9bACYMbprP36z9t1mPESQm5isRrzEufrdtzK+n+2mk/6rldTrcDroUKQ9MJhd6mdi9yweUaA1wkLRM+udqvcN1lHpdsDwqpAuYY+RIouXCMW8gkb2j5P/1aMytmhSDEetz2aSPqKcpPkrJtkDw6OwcXLG68GchQ+ezZZQVw0Y0c238cejZ8kayXsZDyYAwKp0q2OH2vmC8qKP46iIPOUtukEB/l77kz358vOX1/5j4eHNjD+MlnYrCdw9q3EyOUvV9pYHuHWzHB/r6AYuqZx0huAIeY87sfZCFQXuorjnZ6oHdnO7HIWccSGRgFWhPbzniAKfESDnzMjZZNy+RD7bfHvNsORqdHPVLwSKgoEvvhVWpNegucrrB0Ao/aS85bJykrt+3+D6pv7RuZmxhVbjwJq7O/67dMu7dtepn/svyB6yracpMoFJCNQj4UqFxjfX6GKx/oTxHddRHK/4DMSantI+pqB+6hp5L0jbMeb9kE3oS8bBxVC2sKYjfVyCpKjHw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
