travis:
  secure:
    BINSTAR_TOKEN: MkwtGL9wKmtMa0e5x7cbLKiXYOqhduIGWPhh/UXwHP6snxZ1KtTwEIPB1LWkbVFUtiID5+JLH7bQxIZ3viOcmy8VjzMVn73tW2Z0JhvRT+Zr5vf+TyBVV1K1u1vGOMF0FS7V/zYmqJyGB0YlasAQ3ORBCEfBZD7kkoqgjuc5Dvx2C+1NxHDlCHVujWtHO8JrxeF4KBiOLRlissLC3Xr7Esitb/67RgpYzmHuUNj6/QTngXnxZsYI9Rw0t9RSvhPtxpRkJDrgi48ILxO24XMwDpKfg6DAgnOLjcBAHGxC0AM6a8XjQ7h+LasV1VH6wGVpWS7c/RG6BuzzThtvFeLV37EXr7AoElPNLlSgqc+pnwbZsccBYuiyPw4rqx8sHEBZOe9UQTInOSzhe7+nlJxuCQJ24NpFW6ekyO6d4vgsBH0Yahfn+zas+ZgHNDy2yNpRc1Nd8zIgG/04RdVMeU61ovA7g8o/rYJWZdO5ZLH3RhwAs6IrK+J4m4d5i2IxlAoRL5BB+FWfn1If3XoSC6l4sB+k8sF6aleJ8UChcwMIm22dvydjPqn1ikZL5AgVJSk54Kp7Bhkn/JfApNTYRXfcd+4Q5KO0ljUA6CrHM7bmcKoZ1EockKm7uirqwjK9Fp7jkJ11SyRZ7orK0V6omGhN9FrjeDT9mTv0DUNB4lZlSQM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
